# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  flake8:
    runs-on: ubuntu-latest
    container: firedrakeproject/firedrake
    strategy:
      fail-fast: false
    steps:
      - name: Change permissions for checkout
        run: sudo chmod -R 777 /__w
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          . /home/firedrake/firedrake/bin/activate
          python -m pip install --upgrade pip
          python -m pip install .
          pip install flake8
      - name: Lint with flake8 (required action)
        run: |
          . /home/firedrake/firedrake/bin/activate
          # stop the build if there are Errors, Warnings, or pyflakes codes.
          flake8 TTiP --select=E,F,W --show-source --statistics
      - name: Lint with flake8 (recommended action)
        continue-on-error: true
        run: |
          . /home/firedrake/firedrake/bin/activate
          flake8 TTiP tests --select=C,N --statistics
  pylint:
    runs-on: ubuntu-latest
    container: firedrakeproject/firedrake
    strategy:
      fail-fast: false
    steps:
      - name: Change permissions for checkout
        run: sudo chmod -R 777 /__w
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          . /home/firedrake/firedrake/bin/activate
          python -m pip install --upgrade pip
          python -m pip install .
          pip install pylint
      - name: Lint with Pylint (required action)
        run: |
          . /home/firedrake/firedrake/bin/activate
          # Fail on Fatal, Error, or Warning
          pylint --rcfile=setup.cfg TTiP tests/ --disable="R,C"
      - name: Lint with Pylint (recommended action)
        continue-on-error: true
        run: |
          . /home/firedrake/firedrake/bin/activate
          # Report Refactor or Convention but do not fail.
          pylint --rcfile=setup.cfg TTiP tests/ --disable="F,E,W"

  test:
    runs-on: ubuntu-latest
    container: firedrakeproject/firedrake
    strategy:
      fail-fast: false
    steps:
      - name: Change permissions for checkout
        run: sudo chmod -R 777 /__w
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          . /home/firedrake/firedrake/bin/activate
          python -m pip install --upgrade pip
          python -m pip install .
          pip install pytest
          pip install pytest-cov
      - name: Run Unit tests
        run: |
          . /home/firedrake/firedrake/bin/activate
          export PYTHONPATH="$PWD/TTiP:$PYTHONPATH"
          pytest --cov=TTiP --cov-report=xml -cov-report=term tests/unit
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          flags: unittests
          fail-ci-if-error: true