# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: firedrakeproject/firedrake
    steps:
      - name: Change permissions for checkout
        run: sudo chmod -R 777 /__w
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          . /home/firedrake/firedrake/bin/activate
          python -m pip install --upgrade pip
          python -m pip install .
      - name: Lint with flake8
        run: |
          . /home/firedrake/firedrake/bin/activate
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 TTiP --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 TTiP --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Lint with Pylint
        run: |
          . /home/firedrake/firedrake/bin/activate
          pip install pylint
          pylint -d invalid-name TTiP 
      - name: Test with pytest
        run: |
          . /home/firedrake/firedrake/bin/activate
          pip install pytest
          pytest tests
